services:
  postgres:
    container_name: postgres_dev
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - pg_data:/data/postgres
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always

  rabbitmq:
    container_name: rabbitmq_dev
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

volumes:
  pg_data:
  rabbitmq_data:

networks:
  default:
    driver: bridge
