server:
  port: ${SERVER_PORT}
spring:
  application:
    name: messender-spring

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        region: ${AWS_S3_REGION}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: ${JWT_EXPIRATION}

com:
  example:
    aws:
      s3:
        bucket-name: ${AWS_S3_BUCKET_NAME}